version: '3.3'

services:
  postgres:
    container_name: local_postgres
    image: "postgres:12"
    restart: always
    environment:
      POSTGRES_DB: 'my_database'
      POSTGRES_USER: 'airflow'
      POSTGRES_PASSWORD: 'airflow'
    expose:
      - "5433"
    ports:
      - "5433:5432"
    volumes:
       - postgres:/var/lib/postgresql/data
  db:
    container_name: local_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  postgres:
    driver: local
  my-db:
    driver: local
